
-- ОПТИМАЛЬНОЕ РЕШЕНИЕ: DBMS_LDAP + DBMS_SCHEDULER
-- Архитектурное решение для ежедневной синхронизации AD с Oracle APEX 23.1

-- =====================================================================
-- ЭТАП 1: СОЗДАНИЕ ИНФРАСТРУКТУРЫ
-- =====================================================================

-- 1.1. Создание служебной схемы для синхронизации
CREATE USER AD_SYNC_SERVICE IDENTIFIED BY "SecurePassword123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO AD_SYNC_SERVICE;
GRANT CREATE JOB TO AD_SYNC_SERVICE;
GRANT CREATE PROCEDURE TO AD_SYNC_SERVICE;
GRANT CREATE TABLE TO AD_SYNC_SERVICE;
GRANT CREATE SEQUENCE TO AD_SYNC_SERVICE;
GRANT CREATE VIEW TO AD_SYNC_SERVICE;

-- 1.2. Настройка Network ACL для LDAP доступа
BEGIN
    DBMS_NETWORK_ACL_ADMIN.CREATE_ACL(
        acl         => 'ad_ldap_access.xml',
        description => 'ACL for Active Directory LDAP access',
        principal   => 'AD_SYNC_SERVICE',
        is_grant    => TRUE,
        privilege   => 'connect',
        start_date  => SYSDATE,
        end_date    => NULL
    );

    DBMS_NETWORK_ACL_ADMIN.ASSIGN_ACL(
        acl  => 'ad_ldap_access.xml',
        host => 'your-ad-server.domain.com',
        lower_port => 389,
        upper_port => 636
    );

    COMMIT;
END;
/

-- =====================================================================
-- ЭТАП 2: СОЗДАНИЕ ТАБЛИЦ И СТРУКТУР ДАННЫХ  
-- =====================================================================

-- 2.1. Основная таблица пользователей AD
CREATE TABLE AD_SYNC_SERVICE.AD_USERS (
    user_id                 VARCHAR2(50) PRIMARY KEY,
    sam_account_name        VARCHAR2(256) NOT NULL,
    user_principal_name     VARCHAR2(256),
    distinguished_name      VARCHAR2(2000),
    display_name           VARCHAR2(256),
    given_name             VARCHAR2(256),
    surname                VARCHAR2(256),
    email_address          VARCHAR2(256),
    department             VARCHAR2(256),
    title                  VARCHAR2(256),
    manager_dn             VARCHAR2(2000),
    manager_sam_account    VARCHAR2(256),
    telephone_number       VARCHAR2(50),
    mobile_number          VARCHAR2(50),
    office_location        VARCHAR2(256),
    company                VARCHAR2(256),
    employee_id            VARCHAR2(50),
    employee_type          VARCHAR2(50),
    account_enabled        VARCHAR2(1) DEFAULT 'Y',
    password_last_set      DATE,
    last_logon             DATE,
    when_created           DATE,
    when_changed           DATE,
    object_guid            RAW(16),
    object_sid             VARCHAR2(256),
    user_account_control   NUMBER,
    -- Метаданные синхронизации
    sync_status            VARCHAR2(20) DEFAULT 'ACTIVE',
    first_sync_date        DATE DEFAULT SYSDATE,
    last_sync_date         DATE DEFAULT SYSDATE,
    sync_attempts          NUMBER DEFAULT 0,
    sync_error_message     VARCHAR2(4000),
    created_by             VARCHAR2(100) DEFAULT USER,
    created_date           DATE DEFAULT SYSDATE,
    modified_by            VARCHAR2(100) DEFAULT USER,
    modified_date          DATE DEFAULT SYSDATE
);

-- 2.2. Таблица групп AD
CREATE TABLE AD_SYNC_SERVICE.AD_GROUPS (
    group_id               VARCHAR2(50) PRIMARY KEY,
    sam_account_name       VARCHAR2(256) NOT NULL,
    distinguished_name     VARCHAR2(2000),
    display_name          VARCHAR2(256),
    description           VARCHAR2(1000),
    group_type            VARCHAR2(50),
    group_scope           VARCHAR2(50),
    object_guid           RAW(16),
    object_sid            VARCHAR2(256),
    when_created          DATE,
    when_changed          DATE,
    -- Метаданные синхронизации  
    sync_status           VARCHAR2(20) DEFAULT 'ACTIVE',
    first_sync_date       DATE DEFAULT SYSDATE,
    last_sync_date        DATE DEFAULT SYSDATE,
    created_by            VARCHAR2(100) DEFAULT USER,
    created_date          DATE DEFAULT SYSDATE,
    modified_by           VARCHAR2(100) DEFAULT USER,
    modified_date         DATE DEFAULT SYSDATE
);

-- 2.3. Таблица членства в группах
CREATE TABLE AD_SYNC_SERVICE.AD_USER_GROUPS (
    membership_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_sam_account      VARCHAR2(256) NOT NULL,
    group_sam_account     VARCHAR2(256) NOT NULL,
    membership_type       VARCHAR2(20) DEFAULT 'DIRECT',
    added_date            DATE DEFAULT SYSDATE,
    sync_status           VARCHAR2(20) DEFAULT 'ACTIVE',
    last_sync_date        DATE DEFAULT SYSDATE,
    CONSTRAINT fk_user_groups_user FOREIGN KEY (user_sam_account) 
        REFERENCES AD_USERS(sam_account_name),
    CONSTRAINT fk_user_groups_group FOREIGN KEY (group_sam_account) 
        REFERENCES AD_GROUPS(sam_account_name),
    CONSTRAINT uk_user_group UNIQUE (user_sam_account, group_sam_account)
);

-- 2.4. Таблица логов синхронизации
CREATE TABLE AD_SYNC_SERVICE.AD_SYNC_LOG (
    log_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_session_id       VARCHAR2(50) NOT NULL,
    sync_type             VARCHAR2(50) NOT NULL, -- USERS, GROUPS, MEMBERSHIPS
    sync_operation        VARCHAR2(20) NOT NULL, -- INSERT, UPDATE, DELETE
    object_identifier     VARCHAR2(256),
    sync_status           VARCHAR2(20) NOT NULL, -- SUCCESS, ERROR, WARNING
    start_time            TIMESTAMP DEFAULT SYSTIMESTAMP,
    end_time              TIMESTAMP,
    duration_seconds      NUMBER,
    records_processed     NUMBER DEFAULT 0,
    records_success       NUMBER DEFAULT 0,
    records_error         NUMBER DEFAULT 0,
    error_message         VARCHAR2(4000),
    detailed_log          CLOB,
    created_by            VARCHAR2(100) DEFAULT USER,
    created_date          DATE DEFAULT SYSDATE
);

-- 2.5. Таблица конфигурации синхронизации
CREATE TABLE AD_SYNC_SERVICE.AD_SYNC_CONFIG (
    config_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_group          VARCHAR2(50) NOT NULL,
    config_name           VARCHAR2(100) NOT NULL,
    config_value          VARCHAR2(4000),
    config_description    VARCHAR2(1000),
    is_encrypted          VARCHAR2(1) DEFAULT 'N',
    is_active             VARCHAR2(1) DEFAULT 'Y',
    created_by            VARCHAR2(100) DEFAULT USER,
    created_date          DATE DEFAULT SYSDATE,
    modified_by           VARCHAR2(100) DEFAULT USER,
    modified_date         DATE DEFAULT SYSDATE,
    CONSTRAINT uk_config_group_name UNIQUE (config_group, config_name)
);

-- Вставка базовой конфигурации
INSERT INTO AD_SYNC_SERVICE.AD_SYNC_CONFIG (config_group, config_name, config_value, config_description) VALUES
('LDAP', 'HOST', 'your-ad-server.domain.com', 'LDAP Server Hostname'),
('LDAP', 'PORT', '389', 'LDAP Server Port'),
('LDAP', 'USE_SSL', 'N', 'Use SSL Connection (Y/N)'),
('LDAP', 'SSL_PORT', '636', 'LDAP SSL Port'),
('LDAP', 'BASE_DN', 'DC=domain,DC=com', 'Base Distinguished Name'),
('LDAP', 'USER_BASE_DN', 'OU=Users,DC=domain,DC=com', 'User Search Base DN'),
('LDAP', 'GROUP_BASE_DN', 'OU=Groups,DC=domain,DC=com', 'Group Search Base DN'),
('LDAP', 'BIND_DN', 'CN=ldap_service,OU=Service Accounts,DC=domain,DC=com', 'Service Account DN'),
('LDAP', 'BIND_PASSWORD', 'ServicePassword123', 'Service Account Password'),
('SYNC', 'BATCH_SIZE', '1000', 'Records per batch'),
('SYNC', 'MAX_RETRIES', '3', 'Maximum retry attempts'),
('SYNC', 'TIMEOUT_SECONDS', '300', 'LDAP operation timeout'),
('SYNC', 'ENABLE_USER_SYNC', 'Y', 'Enable user synchronization'),
('SYNC', 'ENABLE_GROUP_SYNC', 'Y', 'Enable group synchronization'),
('SYNC', 'ENABLE_MEMBERSHIP_SYNC', 'Y', 'Enable membership synchronization'),
('SYNC', 'DELETE_MISSING_USERS', 'N', 'Delete users not found in AD'),
('SYNC', 'EMAIL_NOTIFICATIONS', 'admin@company.com', 'Email for notifications'),
('FILTERS', 'USER_FILTER', '(&(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 'Active users filter'),
('FILTERS', 'GROUP_FILTER', '(objectClass=group)', 'Groups filter'),
('SCHEDULE', 'DAILY_TIME', '02:00:00', 'Daily sync time'),
('SCHEDULE', 'TIMEZONE', 'Europe/Moscow', 'Timezone for scheduling');

COMMIT;







/
