#!/bin/bash

EXPORT_BASE="/home//APEX/bi_portal"
EXPORT_DIR="$EXPORT_BASE/export_$(date +%Y%m%d_%H%M%S)"

# Экспорт приложения
apex export -applicationid 112 -split -dir "$EXPORT_DIR"

# Удаляем папки экспортов старше 7 дней с диска и из git
find "$EXPORT_BASE" -maxdepth 1 -type d -name "export_*" -mtime +7 -exec rm -rf {} \;
git rm -r $(find "$EXPORT_BASE" -maxdepth 1 -type d -name "export_*" -mtime +7) 2>/dev/null

cd "$EXPORT_BASE"
git add .
git commit -m "Автоматический экспорт APEX $(date '+%Y-%m-%d %H:%M:%S')"
git push origin master
